services:
  - type: web
    name: vin-scanner-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install certifi --upgrade
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9
      - key: PYTHONUNBUFFERED
        value: true
      - key: TZ
        value: UTC
      - key: SSL_CERT_FILE
        value: /etc/ssl/certs/ca-certificates.crt
      - key: REQUESTS_CA_BUNDLE
        value: /etc/ssl/certs/ca-certificates.crt
    healthCheckPath: /