services:
  - type: web
    name: vin-scanner-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: MONGO_URI
        sync: false
      - key: API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9
      - key: PYTHONUNBUFFERED
        value: true
      - key: TZ
        value: UTC
    healthCheckPath: /